### ISSUE TITLE
No frame readed (requestFrame returns nullptr)

### ISSUE THREAD

**Issue by fabian57fabian** [ArduCAM/Arducam_tof_camera#53]
OS: Raspbian 11 bullseye
Arducam version: arducam-tof-sdk-dev                  0.1.0                            armhf

I tested with commit from last month and it worked (cpp preview_depth).
Then i pulled newest updates and now it won't work.
Every time i call `tof.requestFrame(200);` , it returns a `nullptr` .

Cam is connected before, i opened it with Arducam::Connection::CSI and started with Arducam::FrameType::DEPTH_FRAME.

What did the new commits break?

**Comment by dennis-ard** [comment]
This update only adds support for media-controller, there is no need to add `media-controller=0` in the config.txt file.
Maybe you can use the following command to check whether the camera has frame rate output
```Shell
v4l2-ctl -d0 --set-fmt-video=width=240,height=180,pixelformat='Y12 ' --stream-mmap --stream-count=-1
```
If there is a frame rate but return `nullptr `, we can provide you with an old version of the SDKfor testing.

**Comment by fabian57fabian** [comment]
I tried and got following output:
`<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.58 fps, dropped buffers: 10
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.31 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 120.04 fps`

I also checked and the last working version was from Apr 11, (commit f8b8facdf613edad1d66d8380afc62bef0a53595)

How can i install the old sdk working until Apr 11?

**Comment by fabian57fabian** [comment]
Just pulled old commit, tested, pulled the newest version and now it works.
Honestly still don't know what did not work, but now it's ok.
