### ISSUE TITLE
Does this Time-Of-Flight camera support USB?

### ISSUE THREAD

**Issue by fumin** [ArduCAM/Arducam_tof_camera#54]
I wonder if it supports connecting using a USB?
My main concern is I only have an ordinary desktop with only USB, and I want to connect the TOF camera to it.

In this github repo, you say the the TOF camera supports USB

https://github.com/ArduCAM/Arducam_tof_camera

However, nowhere in your TOF camera homepage

https://www.arducam.com/time-of-flight-camera-raspberry-pi/

nor your getting started guide mentions USB

https://www.arducam.com/downloads/arducam-tof-camera-getting-started.pdf

Therefore, I am confused. Does your TOF camera support USB?

**Comment by fumin** [comment]
@dennis-ard Thanks for your info.
Since the TOF camera connects with MIPI CSI, I suppose I need to get this shield:

https://www.uctronics.com/index.php/arducam-mipi-adapter-board-for-usb3-camera-shield.html

However, that page says this adapter is *discontinued*.

I would how would you suggest we proceed?

**Comment by dennis-ard** [comment]
Sorry, I don't know the company's product situation,
maybe you can send an email to sales@arducam.com to inquire about purchasing.

**Comment by fumin** [comment]
@dennis-ard got you, thanks, I will contact sales
