### ISSUE TITLE
Can't install ArducamDepthCamera in 32-bit Bulleyes via pip

### ISSUE THREAD

**Issue by BeamNC** [ArduCAM/Arducam_tof_camera#59]
Hi,
I can't install ArducamDepthCamera package via pip.
I've followed the instruction on this [page](https://docs.arducam.com/Raspberry-Pi-Camera/Tof-camera/Getting-Started/) and also this repository to install dependencies.

When I tried to install ArducamDepthCamera via pip, I got this error.

`ERROR: Could not find a version that satisfies the requirement ArducamDepthCamera
ERROR: No matching distribution found for ArducamDepthCamera`

Does this package support 32-bit OS?

Here's my system configuration.
Raspi zero w
OS: Raspberry Pi OS (32-bit) Bulleye, released date: 2023-05-03
Python: 3.9.2

**Comment by dennis-ard** [comment]
Hi,
We sincerely apologize for any inconvenience caused. In version 1.1.2, we have made updates to the pip package to ensure compatibility with the armv6l architecture.
